
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://127.0.0.1:3306/w?characterEncoding=utf-8&autoReconnect=true&failOverReadOnly=false&useSSL=true&serverTimezone=UTC
    username: root
    password: root
  servlet:
    multipart:
      ## 上传文件总的最大值
      max-request-size: 10MB
      ## 单个文件的最大值
      max-file-size:  10MB

server:
  port: 5000
#aliyun:
#  oss:
#    access-id:   LTAI4FrF1XQdoFpc9R6JmGDd
#    access-key:  SvxnWfFxfFE3huQ6zY5rAWLQ0uBWCK
#    bucket:      ctrl010
#    endpoint:    oss-cn-chengdu.aliyuncs.com
#    dir:         images/
#    expire:      300 # 签名有效期(S)

#//ctrl010.oss-cn-chengdu.aliyuncs.com
## OSS相关配置信息
aliyun:
  oss:
    endpoint: oss-cn-chengdu.aliyuncs.com # oss对外服务的访问域名
    accessKeyId: LTAI4FrF1XQdoFpcR6JmGDd # 访问身份验证中用到用户标识
    accessKeySecret: SvxnWfFxfFE3huQ6z5rAWLQ0uBWCK # 用户用于加密签名字符串和oss用来验证签名字符串的密钥
    bucketName: ctrl010 # oss的存储空间
    policy:
      expire: 300 # 签名有效期(S)
    maxSize: 10 # 上传文件大小(M)
    callback: http://localhost:8080/aliyun/oss/callback/ # 文件上传成功后的回调地址
    urlPrefix: http://ctrl010.k1772714.club/
    dir:
      prefix: images/ # 上传文件夹路径前缀
